### ISSUE TITLE
Registed Module Not Found

### ISSUE THREAD

**Issue by dain40** [kkirsche/apispec-pydantic-plugin#24]
I tested it by writing the code as follows.

```python
from apispec import APISpec
from pydantic import BaseModel, Field
from apispec_pydantic_plugin import PydanticPlugin


from pprint import pprint

spec = APISpec(
    title="Gisty",
    version="1.0.0",
    openapi_version="3.0.2",
    info=dict(description="A minimal gist API"),
    plugins=[PydanticPlugin()],
)

class GistSchema(BaseModel):
    id: int = Field(title="id", description="id")
    content: str = Field(title="content", description="content")

spec.components.schema("Gist", schema=GistSchema)
spec.path(
    path = "/hello", 
    operations = dict(
        get=dict(
            responses={"200": {"content": {"application/json": {"schema": "Gist"}}}}
        )
    )
)

pprint(spec.to_dict())
```

However, this code resulted in a "module not found" error.
it works properly when changed to MarshmallowPlugin under the same conditions.

**Comment by dain40** [comment]
This issue works correctly when the openapi_version major version is set to 2.

**Comment by kkirsche** [comment]
I'll have to take a look at what I'm doing in the app I'm using this in. We're using openapi_version 3.0.2 without any issues.

This wouldn't load `GistSchema` though via pedantic as you need to import `ApiBaseModel` from `apispec_pydantic_plugin` so that we can hook the import and add it to the component registry. I didn't find a way to hook Pydantic's module from outside of it (for `__init_subclass__`) so if you are aware of a way, I'd love to implement that so that people don't need to use `ApiBaseModel` instead of `BaseModel`, since the only thing I'm doing is wrapping it for registry management

**Comment by dain40** [comment]
Thank you. Your advice helped solve the problem. I confirmed that it works properly after changing BaseModel to ApiBaseModel.
